# Generated by Django 2.0.4 on 2018-04-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('university_name', models.CharField(default='',
                                                     max_length=200)),
                ('university_address', models.TextField(max_length=400)),
                ('food_quality', models.IntegerField(choices=[
                 (1, 'bad'), (2, 'bearable'), (3, 'medium'), (4, 'good'),
                 (5, 'select')],default=5)),
                ('further_complain', models.TextField()),
            ],
        ),
    ]
